Set Layouts via Preference Page
eclipse/windowbuilder pull request #182
Opened 2022-04-12 08:33 UTC by MarcelS4

This closes issue #181 

Users are now able to set the specific layouts they want to be made available in Windowbuilder. By default all layouts are available.
Following is a screenshot of the preference page in Swing:
![image](https://user-images.githubusercontent.com/92920738/162916671-06aeb2e7-9c6e-40f5-9810-50b26fa0db67.png)
Following is a screenshot of the preference page in SWT:
![image](https://user-images.githubusercontent.com/92920738/162916829-e6fb1c76-3791-4ae0-ab9d-59f30eacdd3f.png)

Below the preferences are set to only include the border layout, the UI changes can be seen in the layout group on the designer palette as well as in the context menu and layout dropwdown in the Properties view.
![image](https://user-images.githubusercontent.com/92920738/162917472-25fee1a1-4785-4393-bbb1-4ea3596908db.png)

![image](https://user-images.githubusercontent.com/92920738/162917237-aa435a2c-8263-42c6-9628-f5a85accb698.png)
![image](https://user-images.githubusercontent.com/92920738/162917308-db078e1c-9e90-4d4d-a652-ef2040ff2916.png)

2022-04-21 09:44 UTC, vogella commented
@MarcelS4 new preference UI looks really good but I think you forgot to consider the new preferences for the SWT case.


![image](https://user-images.githubusercontent.com/139910/164427796-89d0dff6-1314-440a-a9ae-e2eb54619fc7.png)

![image](https://user-images.githubusercontent.com/139910/164427968-e415e2a0-8911-4a24-a453-7fa2130a99b4.png)

Can you check and update the review?

2022-04-21 09:45 UTC, vogella requested changes
The SWT use case is currently not considered

2022-04-21 11:19 UTC, vogella commented
please rebase onto latest master in the origin

2022-05-03 06:57 UTC, vogella commented
@MarcelS4 did you fix the SWT use case?

2022-05-03 06:58 UTC, MarcelS4 commented
Yes, the SWT use case should now work like the swing use case

2022-05-03 09:15 UTC, wimjongman commented
Congratulations on your committer election, @MarcelS4! 🎉

2022-05-03 09:19 UTC, vogella commented
Thanks, Marcel, testing it now!

2022-06-08 07:10 UTC, vogella commented
Please combine both commits

2022-06-10 06:36 UTC, MarcelS4 commented
@vogella Some WB tests fail (that didnt fail before), specifically in the SWT test suite. I've tested these on other branches as well, branches that we know they worked on. Any idea what could've caused this?

It occurs in: 

- org.eclipse.wb.tests.designer.swt.model.property.ResourceManagerTest 
- org.eclipse.wb.tests.designer.swt.model.property.SWTResrouceManagerTest
- org.eclipse.wb.tests.designer.swt.model.property.SWTResourceManagerTest

The errors that occur are:

- Java Model Exception: Error in Java Model (code 977): /TestProject/src/test/Test.java already exists in target
- java.lang.ClassNotFoundException: org.eclipse.wb.swt.SWTResourceManager

I recall you mentioning you had issues with your SWT tests, do these issues look familiar to you?

2022-06-10 07:48 UTC, vogella commented
@MarcelS4 I had seem them also but only if I used Eclipse during the test run. Can this also be the case for you?

2022-06-10 07:51 UTC, MarcelS4 commented
I didnt use eclipse during the testing but I did use my computer at the time of the tests. I'll try running them without touching my system and see if that does the trick.

2022-06-10 09:08 UTC, MarcelS4 commented
I've run the tests and didnt touch anything during the test runs but still no luck

2022-06-10 09:40 UTC, vogella commented
IIRC I had this during the review of one of the library changes. If you revert both library changes do you still get the error?

2022-07-05 13:57 UTC, vogella commented
Can you check LayoutManagersTest#test_customImplementationOf_LayoutManager? This test fails with this change and looks related.

2022-07-11 13:38 UTC, merged