Updated Commons Collections lib and moved to Target platform
eclipse/windowbuilder pull request #253
Opened 2022-05-24 09:54 UTC by MarcelS4

Updated the commons-collections library and moved it to the target
platform file. The necessary code changes were made to fix compile
issues and as a result commons-primitives was removed as it was no
longer necessary.

This change was necessary to avoid security vulnerability

2022-05-24 09:58 UTC, MarcelS4 commented
Dependencies Update #252

2022-05-24 10:52 UTC, wimjongman commented
Marcel, All, please assign milestones and connect PR's to an issue so that we have our new and noteworthy, and release documentation up to date.

![image](https://user-images.githubusercontent.com/180969/170018368-12538d52-2bad-4c20-b576-4ecbcb7a34e4.png)

2022-05-31 10:55 UTC, vogella commented
@MarcelS4 this seems to contains also other changes, please "cleanup" the commit so that it only contains changes related to the lib change.

2022-06-01 09:51 UTC, MarcelS4 commented
Ran the WindowBuilderTests test suite and no errors or failing tests appear

2022-06-01 09:58 UTC, vogella commented
Great. Thanks.

2022-06-01 10:04 UTC, vogella commented
Still a lot of unrelated format changes. Can you undo them?

2022-06-01 10:08 UTC, MarcelS4 commented
I'll look into it. but I just copied and pasted the previous commit's line by line so I dont know how they got in there, but will look into it and change it

2022-06-07 08:24 UTC, vogella commented
I handle the formatting changes via a new pull request

2022-06-07 09:56 UTC, vogella requested changes

2022-06-07 09:56 UTC, vogella commented on org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/PropertyTable.java
> -    addListener(SWT.Dispose, new Listener() {
Will move this to another PR

2022-06-07 09:56 UTC, vogella commented on org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/external/ExternalFactoriesHelper.java
> +      public void registryChanged(IRegistryChangeEvent event) {
Will move to another PR

2022-06-07 11:50 UTC, vogella commented
Thanks @MarcelS4

2022-06-07 11:50 UTC, closed without merging